// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmAFfHOZZHuAASRWK5xLe66DgtmXgk2DU',
    appId: '1:646949033633:web:fbc80da27b9752840702e0',
    messagingSenderId: '646949033633',
    projectId: 'thermal-origin-425102-c7',
    authDomain: 'thermal-origin-425102-c7.firebaseapp.com',
    databaseURL: 'https://thermal-origin-425102-c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thermal-origin-425102-c7.appspot.com',
    measurementId: 'G-3HW9041BXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmPITXRCDb87RLV6-H5WwVBgHp3zSaeto',
    appId: '1:646949033633:android:526ed796cf8b208d0702e0',
    messagingSenderId: '646949033633',
    projectId: 'thermal-origin-425102-c7',
    databaseURL: 'https://thermal-origin-425102-c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thermal-origin-425102-c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgB59g7E8s_aYdUwDM81ekv9lh1KFgPRw',
    appId: '1:646949033633:ios:3852574d841d569c0702e0',
    messagingSenderId: '646949033633',
    projectId: 'thermal-origin-425102-c7',
    databaseURL: 'https://thermal-origin-425102-c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thermal-origin-425102-c7.appspot.com',
    iosBundleId: 'com.example.albaypark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgB59g7E8s_aYdUwDM81ekv9lh1KFgPRw',
    appId: '1:646949033633:ios:3852574d841d569c0702e0',
    messagingSenderId: '646949033633',
    projectId: 'thermal-origin-425102-c7',
    databaseURL: 'https://thermal-origin-425102-c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thermal-origin-425102-c7.appspot.com',
    iosBundleId: 'com.example.albaypark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmAFfHOZZHuAASRWK5xLe66DgtmXgk2DU',
    appId: '1:646949033633:web:fc1d6c4469c91e950702e0',
    messagingSenderId: '646949033633',
    projectId: 'thermal-origin-425102-c7',
    authDomain: 'thermal-origin-425102-c7.firebaseapp.com',
    databaseURL: 'https://thermal-origin-425102-c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thermal-origin-425102-c7.appspot.com',
    measurementId: 'G-7SSLGDXYRX',
  );
}
